name: Make Command
description: Runs a make command within the image
inputs:
  image-name:
    description: Image name
    required: true
  artifact-name:
    description: Prefix used for the cached CI image artifact
    required: true
  make-command:
    description: Make command to run linting
    required: true
runs:
  using: composite
  steps:
    - name: Download CI image cache
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}-${{ github.sha }}-cache
        path: /tmp

    - name: Restore CI image
      shell: bash
      run: |
        docker load --input "/tmp/${{ inputs.artifact-name }}-${{ github.sha }}.tar"

    - name: Run Make Command
      shell: bash
      run: |
        docker run --rm \
          --workdir /workspace \
          --volume "${{ github.workspace }}:/workspace" \
          "${{ inputs.image-name }}:${{ github.sha }}" \
          make ${{ inputs.make-command }}
