name: Cleanup CI Cache
description: Removes all artifacts created only for the CI
inputs:
  image-name:
    description: Image name
    required: true
runs:
  using: composite
  steps:
    - name: Remove image artifact
      uses: geekyeggo/delete-artifact@v4
      with:
        name: ${{ inputs.image-name }}-${{ github.sha }}-cache
        failOnError: false

    - name: Remove SBOM artifact
      uses: geekyeggo/delete-artifact@v4
      with:
        name: ${{ inputs.image-name }}-${{ github.sha }}-sbom-cache
        failOnError: false
