name: Cleanup CI Cache
description: Removes all artifacts created only for the CI
inputs:
  artifact-name:
    description: Prefix used for the CI cache and SBOM artifacts
    required: true
runs:
  using: composite
  steps:
    - name: Remove image artifact
      uses: geekyeggo/delete-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}-${{ github.sha }}-cache
        failOnError: false

    - name: Remove SBOM artifact
      uses: geekyeggo/delete-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}-${{ github.sha }}-sbom-cache
        failOnError: false
