name: License Check
description: Runs License Check
inputs:
  image-name:
    description: Image name
    required: true
runs:
  using: composite
  steps:
    - name: Download SBOM
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image-name }}-${{ github.sha }}-sbom-cache
        path: /tmp

    - name: Run license check
      uses: MaibornWolff/purl-patrol@v1.6.2
      with:
        SBOM_PATH: /tmp/${{ inputs.image-name }}-${{ github.sha }}.sbom
        LICENSE_POLICY_PATH: sbom/license_policy.json
        BREAK_ENABLED: true